## Settings
title: CIT 480
owner: 
url: 
baseurl: 
permalink: 
description: "This is used to post blogs for CIT 480"
markdown: 
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: 
github: dsr88068
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: 
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"